class ConnectionClosed(Exception): pass
class UserNotFound(Exception): pass
class AccountPrivate(Exception): pass
class Blacklisted(Exception): pass
class Recording(Exception): pass
class BrowserExtractor(Exception): pass
class GenericReq(Exception): pass
class FFmpeg(Exception): pass
class StreamLagging(Exception): pass